# Application port
server.port=8081

# Root logging level
logging.level.root=INFO

# Package-specific logging level
logging.level.com.deepak.demo=DEBUG

# Log format
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
