apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-service
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
  selector:
    app: {{ .Values.appName }}
