version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root   # nécessaire pour les permissions
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - /var/lib/jenkins:/var/jenkins_home

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    ports:
      - "9090:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs

  demo-app:
    image: dali999/demo-java-app:V1.0
    container_name: demo-app
    ports:
      - "8082:8080"   # ⚠️ j’ai changé pour éviter conflit avec Jenkins
    restart: always

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
