replicaCount: 2

image:
  repository: dali999/demo-java-app   # Ton repo Docker Hub
  pullPolicy: IfNotPresent
  tag: "V1.0"  # remplacé automatiquement par Jenkins

appName: demo-java-app
namespace: app

service:
  type: NodePort
  port: 8081       # port de l’application
  targetPort: 8081 # doit correspondre à ton futur Dockerfile (EXPOSE 8081)
  nodePort: 30081  # port externe (VM) => http://<VM_IP>:30081

