name: Notify on Push

# Déclenche le workflow sur chaque commit sur main
on:
  push:
    branches:
      - main

jobs:
  email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: "Nouveau commit dans devops-demo-project"
          from: ${{ secrets.EMAIL_USER }}
          to: "khlifabanneni707@gmail.com"
          body: |
            Un nouveau commit a été poussé sur la branche main.
            Repo: dali999999/devops-demo-project
            Commit message: ${{ github.event.head_commit.message }}

