name: Notify on Push

on:
  push:
    branches:
      - main

jobs:
  email:
    runs-on: ubuntu-latest
    steps:
      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: "New commit pushed to main"
          to: "mohamed.ali.jaouadiii@gmail.com"
          body: |
            Un commit a été poussé sur la branche main.

